### ISSUE TITLE
XML.xslt()

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-xml#1]
Let's add a method for XSL transformation of XML

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#248](https://github.com/jcabi/jcabi-xml/issues/248), [#249](https://github.com/jcabi/jcabi-xml/issues/249) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#249](https://github.com/jcabi/jcabi-xml/issues/249), [#522](https://github.com/jcabi/jcabi-xml/issues/522) are still not solved; solved: [#248](https://github.com/jcabi/jcabi-xml/issues/248).
