### ISSUE TITLE
XPathContext is not immutable and thread-safe

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#100]
The class `com.jcabi.xml.XPathContext` is not immutable and thread-safe as it's documentation states.

This class has `mutator/setter` methods that can bring about change/modification after original initialization of an instance of this class.

```
com.jcabi.xml.XPathContext.add(String, Object);
com.jcabi.xml.XPathContext.merge(NamespaceContext);
```

Moreover, if multiple threads execute these methods there will be `ConcurrentModifications` of an instance of this class making it not thread safe.

This class needs to be revised with `synchronized` methods or `ReentrantLock` as specified in the `Java API`.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@simonjenga this is fixed already, I believe
