### ISSUE TITLE
StrictXML is not immutable and thread-safe

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#101]
The class `com.jcabi.xml.StrictXML` is not immutable and thread-safe as it's documentation states.

This class has `mutator/setter` methods that can bring about change/modification after original initialization of an instance of this class.

```
com.jcabi.xml.StrictXML.registerNs(String, Object);
com.jcabi.xml.StrictXML.merge(NamespaceContext);
```

The method `com.jcabi.xml.StrictXML.print(Collection<SAXParseException>)` uses `java.util.ArrayList<String>` which is not synchronized.

The method `com.jcabi.xml.StrictXML.join(Iterable<?>, String)` uses `java.lang.StringBuilder` which is not safe for use by multiple threads.

If multiple threads execute these methods there will be `ConcurrentModifications` of an instance of this class making it not thread safe.

This class needs to be revised with `synchronized` methods or `ReentrantLock` as specified in the `Java API`.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@simonjenga it's fixed already, I believe
