### ISSUE TITLE
broken link to API page on http://xml.jcabi.com/

### ISSUE THREAD

**Issue by dmzaytsev** [jcabi/jcabi-xml#107]
when I clicked to API link(1)  on http://xml.jcabi.com/ I get valid page
but if I clicked to link (2) I get broken page

![image](https://cloud.githubusercontent.com/assets/9972909/12370938/7c16d536-bc45-11e5-884b-3903a949b2da.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12370923/0151fa38-bc45-11e5-88f7-28741e99605a.png)

I expect valid links to the API

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@dmzaytsev it's fixed already, let's wait for release
