### ISSUE TITLE
Getting ClassNotFoundException

### ISSUE THREAD

**Issue by ifly6** [jcabi/jcabi-xml#113]
I've followed the instructions to add jcabi-xml-0.17.2.jar (from [here](http://xml.jcabi.com/index.html)) to the buildpath. Eclipse is telling me:

```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: com/jcabi/immutable/ArrayMap
Caused by: java.lang.ClassNotFoundException: com.jcabi.immutable.ArrayMap
```

The website tells me 

> The only dependency you need is (you can also download jcabi-xml-0.17.2.jar and add it to the classpath)

So I'm puzzled.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by amihaiemil** [comment]
@ifly6 See page http://xml.jcabi.com/dependencies.html regarding dependencies. 

jcabi-xml-0.17.2.jar is lightweight and does not have the necessary runtime dependencies in it.
If you add jcabi-xml-0.17.2.jar to your classpath directly ("manually"), you also need to add the 3 compile dependencies mentioned on the page. 

However, the easiest way is using Maven... just add the dependency snippet in your pom.xml and you should be good to go. 

If this info was helpful, please close this issue. Thanks.

**Comment by yegor256** [comment]
@ifly6 I'm closing this, since the problem seems to be fixed by @amihaiemil
