### ISSUE TITLE
StrictXMLTest.java:60-63: Fix the tests passesValidXmlUsingXsiSchemaLocation() and...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-xml#115]
Puzzle `96-5e311117` in `src/test/java/com/jcabi/xml/StrictXMLTest.java:60-63` has to be resolved: Fix the tests passesValidXmlUsingXsiSchemaLocation() and rejectsInvalidXmlUsingXsiSchemaLocation() which started failing with exception from SaxParser (http://maven.apache.org/maven-v4_0_0.xsd; White spaces are required between publicId and systemId).... The puzzle was created by Mihai Andronache on 20-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@nikoladespotoski it's in your hands now, please proceed

**Comment by NikolaDespotoski** [comment]
@dmarkov assign someone else.

**Comment by dmarkov** [comment]
> @dmarkov assign someone else.

@nikoladespotoski no problem, I will try to find somebody else

**Comment by dmarkov** [comment]
@amihaiemil please go ahead with this task, it's yours

**Comment by amihaiemil** [comment]
@dmarkov I created PR #118 for this issue. Please assign a reviewer. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov PR #118 has been merged and closed. You can deploy it and close this issue. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #118 for this issue. Please assign a reviewer. Thanks. 

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov ping

**Comment by dmarkov** [comment]
@yegor256 Thanks all, closed

**Comment by dmarkov** [comment]
@amihaiemil Much appreciated! **30 mins** was added to your account, payment ID `AP-71040305SJ5356835`, time spent is 171 hours and 30 mins. +30 added to your rating, at the moment it is: [+195](http://www.netbout.com/b/36402?open=rating)
