### ISSUE TITLE
Questions about working with namespaces in XMLDocument

### ISSUE THREAD

**Issue by skapral** [jcabi/jcabi-xml#129]
Good day. 

[jcabi-xml-nonprefixed-xmlns.tar.gz](https://github.com/jcabi/jcabi-xml/files/817682/jcabi-xml-nonprefixed-xmlns.tar.gz)

Attached a project with unit tests, explaining what I am trying to achieve. 

Generally, I have two questions:
1. Isn't it possible to do namespace registration implicitly and directly from XML provided?
2. I know that it is usually not a good practice, but can't we register non-prefixed namespaces? It's still a valid XML document afterall.
3. Probably I misunderstood something?

Thanks in advance.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by skapral** [comment]
Digging out further, I found this unit test:
https://github.com/jcabi/jcabi-xml/blob/master/src/test/java/com/jcabi/xml/XMLDocumentTest.java#L81

Sounds like what I am looking for. However, I don't quite understand why it is possible to use XPath over xhtml elements here without explicitely registering namespace for http://www.w3.org/1999/xhtml?

**Comment by skapral** [comment]
Ok, after finding https://github.com/jcabi/jcabi-xml/blob/master/src/main/java/com/jcabi/xml/XPathContext.java it all comes to places. This class declares defaults like xhtml. Thats why XPath over xhtml passes while XPath over my schema is not.

No more questions then.
