### ISSUE TITLE
Some issue about xpath & nodes method of XMLDocument in jcabi-xml version0.20

### ISSUE THREAD

**Issue by qiangbro** [jcabi/jcabi-xml#138]
I have a xml document structure as below:

    <structure_info> ---> root node
        <pages>
            <spread pageId="0" fileName="2383-1.pdf"/>
            <spread pageId="1">
                <page fileName="2383-2.pdf"/>
                <page fileName="2383-2.pdf"/>
            </spread>
            <spread pageId="2">
                <page fileName="2383-3.pdf"/>
                <page fileName="2383-3.pdf"/>
            </spread>
            ...
        </pages>
    <structure_info>

I want to visit all spread elements under the `pages` element, one spread by one spread. And then, visit every spread's fileName attributes and its page subnodes, one spread by one spread.
In jcabi-xml 0.19, this code works good:

	XMLDocument structure_info_xml = new XMLDocument(PDFTest.class.getResourceAsStream("inf.xml"));
	List<XML> spreads = structure_info_xml.nodes("//pages/spread");
	System.out.println("spreads.size="+spreads.size());
	for (XML spread : spreads) {
		System.out.println("spread= "+spread);
		System.out.println("pages of this spread: "+spread.nodes("//page"));
		System.out.println("fileNames of this spread: "+spread.xpath("//@fileName"));
	}

In the code, `spread.nodes("//page")` returns all page nodes under the spead node of the current FOR loop, and `spread.xpath("//@fileName")` returns all fileName attributes under the spead node(includes its subnode).

But when i upgrade to jcabi-xml 0.20 (i use maven), it appears something wrong: 
`spread.nodes("//page")` will return all the page nodes under the root node, instead of the current spead node. 
`spread.xpath("//@fileName")` will return all fileName attributes under the root node, instead of the current spead node.

Is this a problem of jcabi-xml 0.20? or I should correct my code to ajust the changes of jcabi-xml?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@qiangbro this is the modification we introduced in 0.20. You can see the reasoning here: https://github.com/jcabi/jcabi-xml/issues/131

**Comment by qiangbro** [comment]
@yegor256
Do you have any immigration guide for jcabi-xml 0.20?
or, What should I do to upgrade my code ( for example, the code I gave above) to keep the compatibility with the new version of jcabi-xml?

**Comment by yegor256** [comment]
@qiangbro instead of `spread.nodes("//page")` just do this: `spread.nodes(".//page")`. I believe this will solve the problem. If not, please let me know.

**Comment by qiangbro** [comment]
@yegor256 Yes, it works.
Now `spread.nodes(".//page")` returns all page nodes under current spread, very good.
thank you.

**Comment by yegor256** [comment]
@qiangbro great, please close the ticket :)

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-xml#138` was not in scope
