### ISSUE TITLE
How to code in Chinese

### ISSUE THREAD

**Issue by shonve** [jcabi/jcabi-xml#147]
How to code in Chinese

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@shonve[/z](https://www.0crat.com/u/shonve) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by shonve** [comment]
no problem

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f43f3117-ffb6-49af-a877-faeef88d2faa, thread: pool-1497-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RUBL5H9](https://www.0crat.com/p/C3RUBL5H9), can't add this XML to 3 existing ones (Close job;{job=gh:jcabi/jcabi-xml#147, reason=GitHub issue was closed},Close job;{job=gh:jcabi/jcabi-xml#147, reason=GitHub issue was closed},Ping;{}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1510671178">
   <created>2018-05-31T06:26:39.215Z</created>
   <type>Close job</type>
   <token>github;jcabi/jcabi-xml;147</token>
   <author>shonve</author>
   <params>
      <param name="job">gh:jcabi/jcabi-xml#147</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-31T06:41:39.216Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: jcabi/jcabi-xml#147, Action: `closed`

**Comment by 0crat** [comment]
@shonve[/z](https://www.0crat.com/u/shonve) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f43f3117-ffb6-49af-a877-faeef88d2faa, thread: AsyncFlush-8
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:jcabi/jcabi-xml#147] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: [1510671178](https://www.0crat.com/C3RUBL5H9/1510671178), Type: "Close job", Author: "shonve"
