### ISSUE TITLE
xpath result List<String> is not transitive

### ISSUE THREAD

**Issue by ilyakharlamov** [jcabi/jcabi-xml#149]
```java
      List<String> xpath = new XMLDocument(
            "<root><item>value</item></root>"
        ).xpath("//root/item/text()");


        List<String> list = Arrays.asList("value");

        System.out.format("list : %s\n", list);
        System.out.format("xpath: %s\n", xpath);

        System.out.format("list.equals(xpath) == %s\n", list.equals(xpath));
        System.out.format("xpath.equals(list) == %s\n", xpath.equals(list));
```

outputs:
> list : [value]
> xpath: [value]
> list.equals(xpath) == true
> xpath.equals(list) == false

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ilyakharlamov would you be interested in submitting a pull request?

**Comment by ilyakharlamov** [comment]
@yegor256 the pull request have been sitting here for 2 weeks: #150

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by yegor256** [comment]
@ilyakharlamov thanks for the fix, the new release is coming...

**Comment by yegor256** [comment]
@ilyakharlamov I believe it's fixed
