### ISSUE TITLE
XMLDocument constructor validation of XML declaration fails on valid XML document

### ISSUE THREAD

**Issue by olegmoz** [jcabi/jcabi-xml#153]
Here is example of valid XML that does not pass validation in XMLDocument constructor.
```
<?xml version="1.0" encoding="utf-8"?>
<package>
...
</package>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@olegmoz you can use version 0.22.2
