### ISSUE TITLE
Xpath is broken

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-xml#154]
I expect the below to pass but if fails - `nodes.get(1).xpath("//x/text()").get(0)` returns "1"
```
        final XML doc = new XMLDocument(
            new ByteArrayInputStream(
                "<root><a><x>1</x></a><a><x>2</x></a></root>".getBytes()
            )
        );
        final List<XML> nodes = doc.nodes("//a");
        MatcherAssert.assertThat(
            nodes.get(0).xpath("//x/text()").get(0),
            Matchers.equalTo("1")
        );
        MatcherAssert.assertThat(
            nodes.get(1).xpath("//x/text()").get(0),
            Matchers.equalTo("2")
        );
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@piotrkot this is because the root node is not changed, when you retrieve `nodes.get(1)`. Your root is still `<root>`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#154` is not assigned, can't get performer

**Comment by piotrkot** [comment]
@yegor256 I would like to have it reopened. I had no time to react to your comment.

Let me explain the problem.
Based on the provided XML, all "a" nodes are found with `doc.nodes("//a")`.
This indeed finds two "a" nodes, and `List<XML> nodes` list contains two XML elements.
With `nodes.get(0)` I access the first one and `nodes.get(0).xpath("//x/text()").get(0)` is equal to "1".
I expect with `nodes.get(1)` I can access the second element from the nodes list. Furthermore, I expect `nodes.get(1).xpath("//x/text()").get(0)` to be equal to "2" as stated in the assert. But this is not true. `nodes.get(1).xpath("//x/text()").get(0)` is equal to "1".
I believe this is a bug.
Please, explain how does it refer to the root.

**Comment by yegor256** [comment]
@piotrkot the XPath location `//` means "search from the ROOT of the document". Thus, no matter where you are at the moment, it will find you everything that exists in the entire document. This is a feature, not a bug :)

**Comment by piotrkot** [comment]
@yegor256 Now I understand. Replacing `xpath("//x/text()")` with `xpath("x/text()")` solves my problem.
Thank you (and good to have you back with short response times :) )

**Comment by yegor256** [comment]
@piotrkot wring.io helps me a lot :)

**Comment by piotrkot** [comment]
@yegor256 Yes, I know. I read you blog regularly :) But this issue was opened for 5 months ;)

**Comment by yegor256** [comment]
@piotrkot now I'm almost live on GitHub)
