### ISSUE TITLE
Reusing `TransformerFactory.newInstance()`

### ISSUE THREAD

**Issue by IngeniariusSoftware** [jcabi/jcabi-xml#169]
@yegor256, I got some result of profiling eo compiler for about 500 eo files:

calling TransformerFactory.newInstance() counted for 35.2% of CPU time and 28.29% of all memory

https://github.com/jcabi/jcabi-xml/blob/07259a2b8fdb49fb1b94db29f10e36837f483f9d/src/main/java/com/jcabi/xml/XSLDocument.java#L367-L371

It is possible to reuse TransformerFactory instance?

CPU:
![image](https://user-images.githubusercontent.com/33983579/185846131-0c40d1dc-3383-4bec-ae71-81ac505d3aa1.png)

Memory:
![image](https://user-images.githubusercontent.com/33983579/185845155-b711a6e2-d604-40d5-89f7-fdfb5ed33279.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware I think the problem is not here, not in this library. Try version 0.27.1 of EO and measure the results again. Please, report your findings directly to `objectionary/eo` repository.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#169` is not assigned, can't get performer
