### ISSUE TITLE
XMLDocumentTest.java:59-64: Implement XPath 2.0...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-xml#213]
The puzzle `221-807476ba` from #221 has to be resolved: 

https://github.com/jcabi/jcabi-xml/blob/f59097aac38174d354a2bf1ccd4d62176dd87605/src/test/java/com/jcabi/xml/XMLDocumentTest.java#L59-L64

The puzzle was created by @volodya-lombrozo on 18-Jul-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@volodya-lombrozo do you know how to fix?

**Comment by volodya-lombrozo** [comment]
@yegor256 I'll take a look

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.0`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#213` is not assigned, can't get performer

**Comment by volodya-lombrozo** [comment]
@yegor256 Thanks
