### ISSUE TITLE
Add more constructors for SaxonDocument

### ISSUE THREAD

**Issue by volodya-lombrozo** [jcabi/jcabi-xml#215]
I've faced with the next problem: I started creating a `SaxonDocument` from the file and realised that `SaxonDocument` doesn't have a constructor for it. So I believe we have to add a couple of useful constructors for `SaxonDocument`.

**Comment by volodya-lombrozo** [comment]
The example, where we need more convenient constructor: https://github.com/objectionary/eo/issues/2278

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#215` is not assigned, can't get performer
