### ISSUE TITLE
StrictXML should be able to look up XSDs from classpath

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-xml#31]
Related to https://github.com/teamed/qulice/issues/273. StrictXML should be able to find XSDs in the classpath in addition to URL lookups. In the example below, it should be able to validate the XML against a classpath resource `spring-beans-2.0.xsd`.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:schemaLocation="http://www.springframework.org/schema/beans spring-beans-2.0.xsd">
</beans>
```

See here for more details: https://stackoverflow.com/questions/2342808/problem-validating-an-xml-file-using-java-with-an-xsd-having-an-include. Note that we have to be able to support classpath *and* external URL lookups with our `LSResourceResolver` implementation.

**Comment by dmarkov** [comment]
@cyberone you're holding this ticket for 13 days already. If it's not finished (and closed) in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -30 to your rating, your total score is [-190](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@cyberone this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-610](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@aoxa it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@aoxa you're working with this ticket for the last 15 days. If it's not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: -210

**Comment by dmarkov** [comment]
@aoxa this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, at the moment it is: -630

**Comment by dmarkov** [comment]
@adko-pl the task is yours, go ahead

**Comment by adko-pl** [comment]
@dmarkov I am unable to progress on this task because of #57

**Comment by yegor256** [comment]
@dmarkov we're blocked by #57 here

**Comment by dmarkov** [comment]
> @dmarkov we're blocked by #57 here

@yegor256 got it, let's wait for #57

**Comment by adko-pl** [comment]
@dmarkov #57 is resolved, now we're blocked by #58 here

**Comment by adko-pl** [comment]
@dmarkov Changes delivered in https://github.com/jcabi/jcabi-xml/pull/59

**Comment by dmarkov** [comment]
> @dmarkov #57 is resolved, now we're blocked by #58 here

@adko-pl issue #57 is closed already

**Comment by dmarkov** [comment]
> @dmarkov #57 is resolved, now we're blocked by #58 here

@adko-pl sure, let's wait for #58, #57

**Comment by adko-pl** [comment]
@dmarkov now we're blocked by #60 here

**Comment by dmarkov** [comment]
> @dmarkov now we're blocked by #60 here

@adko-pl got it, let's wait for #60

**Comment by dmarkov** [comment]
we waited for #57, it is closed already

**Comment by adko-pl** [comment]
@dmarkov changes have been merged https://github.com/jcabi/jcabi-xml/pull/59#issuecomment-76296982

**Comment by dmarkov** [comment]
Issue #58 is already closed (we were waiting for it) Maybe we can continue..

**Comment by adko-pl** [comment]
@dmarkov despite #60 the changes for this task have been merged already, we can close this ticket

**Comment by dmarkov** [comment]
FYI, issue #60 is already closed, and we were waiting for it..

**Comment by adko-pl** [comment]
@dmarkov the changes for this ticket have been merged a month ago https://github.com/jcabi/jcabi-xml/pull/59#issuecomment-76296982, please close this ticket

**Comment by yegor256** [comment]
@adko-pl you should ask ticket reporter to close the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by adko-pl** [comment]
@carlosmiranda please close this ticket

**Comment by carlosmiranda** [comment]
@adko-pl Thanks!

**Comment by dmarkov** [comment]
@adko-pl Much obliged! I have added **30 mins** to your account in payment "AP-2D438667SP010891U", 1320 hours and 58 mins spent

+30 added to your rating, at the moment it is: [+1](http://www.netbout.com/b/35150?open=rating)
