### ISSUE TITLE
StrictXMLTest.java:171-176: This test does nothing useful...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-xml#43]
Puzzle `32-8743edc8` in `src/test/java/com/jcabi/xml/StrictXMLTest.java:171-176` has to be resolved: This test does nothing useful for the moment, to be a real test it needs to mock com.jcabi.xml.StrictXML.newValidator() and new mocked validator should throw few SocketException's while executing javax.xml.validation.Validator.validate(Source) in order to simulate the situation with network problems. For more details, see com.jcabi.xml.StrictXML.validate(XML) as well.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@alevohin the task is yours

**Comment by alevohin** [comment]
@dmarkov PR merged. Please check and close issue.

**Comment by alevohin** [comment]
@dmarkov PR merged. Please check and close issue.

**Comment by dmarkov** [comment]
The issue should be closed..

**Comment by dmarkov** [comment]
@alevohin Much obliged! I've added **30 mins** to your account in payment "50593419"... +30 added to your rating, current score is: [+330](http://www.netbout.com/b/35105?open=rating)
