### ISSUE TITLE
Error in XPathFactory#newInstance

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-xml#46]
While running some of the tests of [rultor](https://github.com/yegor256/rultor) (IndexesRequestsTest, for example), ran into the incorrect config of Saxon 9.1.0.8, used in jcabi-xml code. 

>java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:%path%/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
	at com.jcabi.xml.XMLDocument.<clinit>(XMLDocument.java:84)

This is a [known bug](https://saxonica.plan.io/issues/1944#note-3).

Please upgrade dependency version to the one in which the issue is fixed and release a new version of jcabi-xml.

**Comment by yegor256** [comment]
but jcabi-xml doesn't depend on Saxon... or I miss something?

**Comment by maurezen** [comment]
Checked now - you're right, it does not. Rultor does. Will reopen the issue in rultor.
