### ISSUE TITLE
XSLDocumentTest.stripsXml fails under Windows

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-xml#47]
>`Failed tests:
  XSLDocumentTest.stripsXml:142
Expected: a string containing "<a>\n<b/>\n</a>"
     but: was "<?xml version="1.0" encoding="UTF-8" standalone="no"?>`
`<a>`
`<b/>`
`</a>`
`"`

Test implementation does not account for the system-dependant line separator. Please use `line.separator` system property, `String#format` or other system-agnostic implementation.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@jenya This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 50516543

**Comment by dmarkov** [comment]
@apocarteres the task is yours

**Comment by jenya** [comment]
@dmarkov Why have you reassign this task (and one more other) off me? You gave them to me only yesterday... Or should I always say "I'll take it" on each task?

**Comment by yegor256** [comment]
@jenya we had no feedback from your for a few weeks, that's why decided to remove you from the projects. are you interested to get back?

**Comment by jenya** [comment]
@yegor256 Yes, I'd like to get back back.

**Comment by yegor256** [comment]
ok, please create an account in www.netbout.com and give me your name there, we'll communicate there

**Comment by apocarteres** [comment]
please check and merge PR https://github.com/jcabi/jcabi-xml/pull/48

**Comment by apocarteres** [comment]
@maurezen it's merged. please check

**Comment by dmarkov** [comment]
@apocarteres Thanks a lot, I just topped your account for **30 mins**, transaction ID `50953458`

added +30 to your rating, now it is equal to [+75](http://www.netbout.com/b/35111?open=rating)
