### ISSUE TITLE
Extensive global synchronizations

### ISSUE THREAD

**Issue by lightoze** [jcabi/jcabi-xml#53]
These global synchronizations around resource-intensive code should be avoided:
https://github.com/jcabi/jcabi-xml/blob/master/src/main/java/com/jcabi/xml/XSLDocument.java#L275
https://github.com/jcabi/jcabi-xml/blob/master/src/main/java/com/jcabi/xml/XSDDocument.java#L168
https://github.com/jcabi/jcabi-xml/blob/master/src/main/java/com/jcabi/xml/XSDDocument.java#L184

**Comment by yegor256** [comment]
@lightoze this is on purpose, because DOM is not thread-safe, but we promise that our classes are thread-safe.

**Comment by lightoze** [comment]
Let's look at XLSDocument case first. You create local TransformerFactory and Transformer instances, so you should not worry about them. DOM itself is a potential source of a problem (when the same document is used in concurrent transformations), but in this case synchronization should be on `xml`, `xml.node()` or whatever.

**Comment by yegor256** [comment]
The problem is that creating a local instance of `Transformer` doesn't make it thread safe :( I believe it's full of static properties inside.

**Comment by lightoze** [comment]
Do you want to say that it's impossible to run two concurrent XSL transformations inside the same JVM?That's ridiculous.
Transformer [documentation](http://docs.oracle.com/javase/6/docs/api/javax/xml/transform/Transformer.html) says clearly: An object of this class may not be used in multiple threads running concurrently. Different Transformers may be used concurrently by different threads.

**Comment by yegor256** [comment]
Yes, that's exactly what I'm saying and I have a test that proves it. Take a look: https://github.com/jcabi/jcabi-xml/blob/master/src/test/java/com/jcabi/xml/XSLDocumentTest.java#L72-L98

Try to remove `@Ignore` from the test and then remove synchronization. Then, run `mvn clean test` and you will see what happens.

**Comment by lightoze** [comment]
Just did exactly what you suggested - the test is not failing with removed synchronization. Can you reproduce it yourself now?
Tested with JRE 1.8.0_31 and 1.7.0_76

**Comment by maxonfjvipon** [comment]
@yegor256 I think it can be closed
