### ISSUE TITLE
Repetitive parsing results should be cached

### ISSUE THREAD

**Issue by lightoze** [jcabi/jcabi-xml#54]
Reusing objects is very ineffective because a lot of parsing is done on each request. Most important points for optimization:
- XMLDocument.node()
- Schema parsing in XSDDocument.validate() - result is thread-safe
- Transformer creation in XSLDocument.transformInto() - result is not thread-safe and object synchronization is required

**Comment by yegor256** [comment]
@lightoze I totally agree that `XMLDocument.node()` has to be optimized. Now it's re-parsing the entire document over and over again, on every call.

For other issues you mentioned, please submit separate tickets. We work one ticket per problem. Hope you don't mind :)

Thanks for pointing out to this problem!

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@maurezen it's yours, budget is 30 mins, please go ahead

**Comment by maurezen** [comment]
@yegor256 @lightoze at the moment we can't cache the parsing result, since `XMLDocument` is `@Immutable` and the cacheable result is an interface which is not (either `Document`, `Element` or `Node`). Should we lift the immutability requirements from `XMLDocument` in order to improve performance?

**Comment by yegor256** [comment]
@maurezen we need a workaround. let's try to use an array of `Node` with a single element. I think `@Immutable` will be fine with it

**Comment by maurezen** [comment]
@yegor256 I've tried that, of course. Doesn't work. Had to use a field of 'Object' type.
Created a pull request #56.

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@maurezen thanks!

**Comment by maurezen** [comment]
@yegor256 @lightoze fixed, please close the issue.

**Comment by maurezen** [comment]
@yegor256 @lightoze ping.

**Comment by maurezen** [comment]
@lightoze ping. please close the issue.

@yegor256 what do we do if the issue reporter doesn't show up?

**Comment by lightoze** [comment]
@maurezen I expected that project owner will close it after review.

**Comment by maurezen** [comment]
@lightoze sorry, I should have explicitly asked you to close.

@dmarkov the task is closed.

**Comment by dmarkov** [comment]
@maurezen Thanks for your contribution, **30 mins** was added to your account, payment ID is `52455818`

added +30 to your rating, now it is equal to [+1185](http://www.netbout.com/b/35102?open=rating)
