### ISSUE TITLE
Build fails because of quilice issues

### ISSUE THREAD

**Issue by adko-pl** [jcabi/jcabi-xml#57]
On my Mac and Windows 7 I unable to build the sources because of quilice issues:

    Unable to get XClass for java/lang/StringBuilder 
    java.lang.ArrayIndexOutOfBoundsException: 5747
    <stacktrace> 

[output](https://drive.google.com/file/d/0B3oU0TckBsdzRW16cVVxU2lRLXM/view?usp=sharing) generated using `mvn clean install -Pqulice -l maven.debug.log -X`

**Comment by yegor256** [comment]
what is your environment? Maven, Java? I build it without any issues (maven 3.2.3, java 7, Mac)

**Comment by adko-pl** [comment]
I did more investigation, Java 8 (1.8.0_25) is causing this problem, with Java 1.7.0_71 it works fine.

**Comment by yegor256** [comment]
@adko-pl try now

**Comment by adko-pl** [comment]
@yegor256 it works now, closing the issue
