### ISSUE TITLE
Unable to add new classes due to Copyright 2012-2014 header check

### ISSUE THREAD

**Issue by adko-pl** [jcabi/jcabi-xml#58]
It is impossible to add new classes to the project codebase due to the following qulice check:

    [ERROR] /src/main/java/com/jcabi/xml/ClasspathInput.java[2]: Line does not match expected header line of ' * Copyright (c) 2012-2014, jcabi.com'. (HeaderCheck)

**Comment by yegor256** [comment]
@adko-pl just use the same header as all other `.java` classes have. or I missed the point?

**Comment by adko-pl** [comment]
@yegor256 ok, I've used this workaround, however one day the headers would have to be updated.

**Comment by yegor256** [comment]
@adko-pl the problem with headers is already reported in #41

**Comment by dmarkov** [comment]
@yegor256 please don't close it.. @adko-pl could you please close it, if it is done?

**Comment by yegor256** [comment]
it's a duplicate

**Comment by adko-pl** [comment]
duplicate of #41, should be closed
