### ISSUE TITLE
get rid of AspectJ

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-xml#61]
Let's get rid of AspectJ in this library, it's redundant

**Comment by dmarkov** [comment]
we will find someone to do this task, soon

**Comment by dmarkov** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-b1b18026`

**Comment by dmarkov** [comment]
@tmjee it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by tmjee** [comment]
@dmarkov done in pull #69

**Comment by longtimeago** [comment]
@yegor256 possibly stupid question, just to be sure - do you want to get rid of
1) jcabi-aspects +  AspectJ
2) or  AspectJ only?
Don't know if the second option is possible.

**Comment by yegor256** [comment]
@longtimeago both of them

**Comment by longtimeago** [comment]
@yegor256 thanks, got it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#61` is not assigned, can't get performer
