### ISSUE TITLE
XPath "//" doesn't work on cloned nodes

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-xml#62]
This test doesn't work:

```java
final XML xml = new XMLDocument("<t6><z9 a='433'/></t6>");
final XML root = xml.nodes("/t6").get(0);
MatcherAssert.assertThat(
  root.xpath("//z9/@a").get(0),
  Matchers.equalTo("433")
);
```

**Comment by dmarkov** [comment]
@yegor256 right, I added the `bug` tag

**Comment by dmarkov** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-6df0335a`

**Comment by dmarkov** [comment]
@suseika please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Suseika** [comment]
@yegor256 Can you please clarify what exactly is the undesired behavior? In the test you pushed, an h9 node doesn't seem to be appended to a document.

**Comment by yegor256** [comment]
@Suseika see this test:  1bc7fc1 It fails, but it shouldn't, as I understand

**Comment by yegor256** [comment]
@Suseika this test works fine if we get rid of cloning. But we need cloning to preserve immutability

**Comment by Suseika** [comment]
@yegor256 This issue's title speaks about `XML#node()` method, there is no `XML#node()` call in 1bc7fc1. I still don't see a way to reproduce the problem I'm assigned to, to me 1bc7c1 looks like another problem.

**Comment by yegor256** [comment]
@Suseika you're right, I updated the description of the ticket and its title

**Comment by Suseika** [comment]
@yegor256 Will you please check the PR?

**Comment by Suseika** [comment]
@dmarkov The task is done.

**Comment by yegor256** [comment]
@Suseika thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by Suseika** [comment]
@dmarkov It's been 3 days, are you going to send a payment?

**Comment by dmarkov** [comment]
@suseika thanks, paid, **30 mins** to your account, payment ID is `AP-3VW99570XF804425V`, task took 169 hours and 26 mins to complete

+30 to your rating, your total score is [+60](http://www.netbout.com/b/35381?open=rating)
