### ISSUE TITLE
getParentNode() doesn't work

### ISSUE THREAD

**Issue by kolowheel** [jcabi/jcabi-xml#68]
getParentNode().getParentNode() returns null 

        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-xml</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@kolowheel it's by design in DOM. `getParentNode()` returns `NULL` when there is no parent node (we're at the top of node hierarchy)
