### ISSUE TITLE
StrictXML is not verbose enough

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-xml#70]

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by dmarkov** [comment]
@yegor256 there is a puzzle in this code `70-64aec8f3`/#72, we'll resolve it later

**Comment by dmarkov** [comment]
@yegor256 last puzzled solved `70-64aec8f3`/#72
