### ISSUE TITLE
pom.xml:217-221: This reporting doesn't work, becuase...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-xml#72]
Puzzle `70-64aec8f3` in `pom.xml:217-221` has to be resolved: This reporting doesn't work, becuase of a conflict with Patterns.java file, which is generated on fly and doesn't really have a source. See the log here, for example: http://www.rultor.com/t/5393-146659058 Let's fix it somehow and enable this profile again.... The puzzle was created by Yegor Bugayenko on 8-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@prondzyn please proceed, it's yours

**Comment by prondzyn** [comment]
@dmarkov PR #122 prepared

**Comment by dmarkov** [comment]
> @dmarkov PR #122 prepared

@prondzyn thank you!

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on PR confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on PR confirmation.

@prondzyn no problem, thanks for letting me know

**Comment by prondzyn** [comment]
@dmarkov PR merged. Please close the ticket.

**Comment by prondzyn** [comment]
@dmarkov I have a question. The task was opened by you. But puzzle was created by @yegor256. To whom should I address closing this taks?

**Comment by dmarkov** [comment]
> @dmarkov PR merged. Please close the ticket.

@prondzyn OK

**Comment by dmarkov** [comment]
@yegor256 I'm closing the issue...

**Comment by dmarkov** [comment]
@prondzyn Much obliged! I have added **30 mins** to your account in payment "AP-63C11102NJ440715D", 384 hours and 55 mins spent

+30 added to your rating, current score is: [+0](http://www.netbout.com/b/35715?open=rating)
