### ISSUE TITLE
XmlDocument.registerNs changes parent contrains

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-xml#73]
When running a build with jcabi-xml 0.16.2, hibernate validators 5.0.0.Final and jcabi-aspects 0.22.1 I get following error:
```
javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not alter the parameter constraint configuration, but method public com.jcabi.xml.XML com.jcabi.xml.XMLDocument.registerNs(java.lang.String,java.lang.Object) changes the configuration of public abstract com.jcabi.xml.XML com.jcabi.xml.XML.registerNs(java.lang.String,java.lang.Object).
```

Please fix `XML` and `XMLDocument` to work without such exceptions.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://www.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@krzyk I don't understand how to reproduce this on master branch. Keep in mind that if something doesn't work in your branch, after your changes, it's your job to fix (or skip) that. Or I misunderstood the ticket?

**Comment by krzyk** [comment]
@yegor256 I meant a build of other project. Basically using both jcabi-xml, hibernate validators and jcabi-aspects in a single project results in the above error during a build.
The problem is that the method `registerNs` looks like this in `XML`:
```
    @NotNull(message = "XML is never NULL")
    XML registerNs(
        @NotNull(message = "prefix can't be NULL") String prefix,
        @NotNull(message = "URI can't be NULL") Object uri);
```

And it looks like this in `XmlDocument`:
```

    @Override
    @NotNull(message = "XML is never NULL")
    public XML registerNs(@NotNull final String prefix,
        @NotNull final Object uri) {
...
    }
```

I assume that using `message` in the `@NotNull` in `XML` and not using it in `XmlDocument` causes this warning.

**Comment by yegor256** [comment]
@krzyk hm.. strange. anyway, here is the fix: e5ce3f6

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.4`

**Comment by yegor256** [comment]
@krzyk try 0.16.4

**Comment by krzyk** [comment]
@yegor256 thanks, it fixed the error
