### ISSUE TITLE
inputStream in com.jcabi.xml.ClasspathInput.getStringData() never closes

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#96]
inputStream in ```com.jcabi.xml.ClasspathInput.getStringData()``` never closes

<hr id='w'>

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@simonjenga looks like a bug, thanks

**Comment by dmarkov** [comment]
@simonjenga thanks for the ticket, your account was topped for 15 mins, payment 72455878

**Comment by dmarkov** [comment]
@amihaiemil could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by dmarkov** [comment]
@amihaiemil you're working with this issue for 15 days already. -30 to your rating, your total score is [+30](http://www.netbout.com/b/36402?open=rating)

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by amihaiemil** [comment]
@dmarkov The PR is created and reviewed, waiting for Yegor's approval to merge.

**Comment by amihaiemil** [comment]
@yegor256 Can you have a look at PR #112 and let it mege if everything's ok? Thanks

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil OK, take your time

**Comment by amihaiemil** [comment]
@dmarkov The PR #112 for this has just been merged and closed. Please close this ticket. Thanks.

**Comment by amihaiemil** [comment]
@simonjenga The PR for this ( #112 ) has been merged and closed. Please close this ticket. Thanks.

**Comment by simonjenga** [comment]
@amihaiemil I am reviewing it and I will close it shortly...

**Comment by amihaiemil** [comment]
@simonjenga Can you close this? The PR has also been deployed. Thanks.

**Comment by simonjenga** [comment]
@amihaiemil The variable ```final String data``` is not needed. Let's remove it.

**Comment by amihaiemil** [comment]
@simonjenga Shouldn't you open another issue regarding other changes? The PR has been reviewed and accepted already. Anymore changes I think should be asked in new issues. It's not that I don't want to do it, but if we follow the rules, then this issue will be taken from me before being closed. It will take days again to be reviewed and merged.

**Comment by dmarkov** [comment]
@simonjenga the code made here contains a puzzle `96-5e311117`/#115, which will be resolved soon

**Comment by amihaiemil** [comment]
@yegor256 The author of this issue asks for changes after the PR has been merged, closed and deployed. See my comment above. What do you think? I never came accros this sitiuation before.

**Comment by yegor256** [comment]
@amihaiemil one task may have many pull requests. the task is "done" only when its author is happy. you may have to submit a number of pull requests for that. if the OP is not reasonable and asks too much in scope of one ticket, you may complain to the project architect (myself). but don't expect that your one PR will solve a problem.

**Comment by amihaiemil** [comment]
@dmarkov I created PR #116 for this issue. Please assign a reviewer. Thanks.

**Comment by simonjenga** [comment]
@dmarkov I will be closing this issue ASAP since PR #116 has already been submitted and requires a minimal review which i expect to be done shortly.

@amihaiemil As the Architect has explained to you above, one PR is sometimes not enough to do a fix to an issue. Also, a PR that has been merged, closed and deployed does not guarantee that an issue will be closed by an author. Everyone involved in a project has a responsibility to ensure that the best is being done and therefore you cannot close your eyes and not raise any concern that you see.

**Comment by amihaiemil** [comment]
@simonjenga Sure. Thank you. .

**Comment by simonjenga** [comment]
@dmarkov @amihaiemil :thumbsup: :ok:

**Comment by dmarkov** [comment]
@amihaiemil thanks, I just added **30 mins** to your account, payment `AP-6CA55205YV7277114`, 551 hours and 6 mins spent; +30 to your rating, your total score is [+45](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@simonjenga the last puzzle `96-5e311117`/#115 originated from here solved

**Comment by simonjenga** [comment]
@dmarkov Thanks for reaching out with the update on that puzzle fix.
It was a simple and smart fix from @amihaiemil 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
