### ISSUE TITLE
ClasspathInput#getStringData() should specify encoding type

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#98]
```ClasspathInput.getStringData()``` doesn't specify an encoding type at the line:

```return IOUtils.toString(this.stream);```

This may be a source of encoding problems.

In order to ensure backward compatibility with ```JDK 6```:

```return IOUtils.toString(this.stream, java.nio.charset.Charset.forName("UTF-8"));```

Unlike using ```java.nio.charset.StandardCharsets.UTF_8``` which was introduced with ```JDK 7```.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga definitely a bug, thanks

**Comment by dmarkov** [comment]
@simonjenga many thanks for the report, I topped your account for 15 mins, transaction 72547317

**Comment by dmarkov** [comment]
@piddubnyi the task is yours, go ahead

**Comment by piddubnyi** [comment]
@simonjenga Fixed in #111, Please close.

**Comment by simonjenga** [comment]
@piddubnyi :thumbsup: :ok:
```IOUtils.toString(this.stream, "UTF-8");``` would also do good.

**Comment by dmarkov** [comment]
@piddubnyi thanks, paid, **30 mins** to your account, payment ID is `76498334`, task took 143 hours and 20 mins to complete; added +30 to your rating, now it is equal to [+210](http://www.netbout.com/b/35966?open=rating)
