### ISSUE TITLE
base parameter ClasspathSources.resolve(String, String) is unused

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#99]
```base``` parameter in ```ClasspathSources.resolve(String, String)``` is unused

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@simonjenga how would you suggest to use it?

**Comment by simonjenga** [comment]
@yegor256 When loading a stream from local address, ```href``` and ```base``` are used to try to find and return a resource, which is absolute. They are also used to compose a local path from path component and base.

```
@param path The path to resource to load from
@param base The base of request
```

**Comment by dmarkov** [comment]
@simonjenga many thanks for the bug report, I added 15 mins to your acc, transaction `72934253`

**Comment by dmarkov** [comment]
@ivanjunckes this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@ivanjunckes the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

added -30 to your rating, now it is equal to [-210](http://www.netbout.com/b/36097?open=rating)

**Comment by dmarkov** [comment]
@piddubnyi it's in your hands now, please proceed

**Comment by piddubnyi** [comment]
@simonjenga Fix is merged. Please close the issue.

**Comment by simonjenga** [comment]
@piddubnyi :thumbsup: :ok:

**Comment by dmarkov** [comment]
@piddubnyi thanks, I just added **30 mins** to your account, payment `75784881`, 168 hours and 36 mins spent

added +30 to your rating, now it is equal to [+90](http://www.netbout.com/b/35966?open=rating)
